### ISSUE TITLE
[Feature] 多种登录方式

### ISSUE THREAD

**Issue by wibus-wee** [mogland/core#215]
https://github.com/mogland/core/issues/215#tasklist-block-6b0f7a09-764e-4b9a-8098-2cb144516259

**Comment by ttimochan** [comment]
两步校验可以！ 个人觉得第三方授权没有必要，除非你准备写多用户？

**Comment by wibus-wee** [comment]
> 两步校验可以！ 个人觉得第三方授权没有必要，除非你准备写多用户？

有这个打算的，issues里有提到过
