### ISSUE TITLE
🎉 Mog v2 - Stage 4

### ISSUE THREAD

**Issue by wibus-wee** [mogland/core#605]
## Core

- feat: 内置控制台 #604 @wibus-wee 
- fix: 捕获读取不存在的 env 文件的错误 #606 @wibus-wee 
- feat!: 独立主题系统服务 #607 @wibus-wee 
- fix: ConfigService 无法正常检验和储存类型为数组的值且直接返回错误 #610 @wibus-wee 
- fix: 生产环境下访问内置控制台时返回 404 #612 @MYXXTS 
- feat: 活动传输器支持返回 Promise #615 @MYXXTS 
- ci: Docker 推送活动测试只在主分支中运行 #616 @MYXXTS
- perf: 将配置转化为对象 https://github.com/mogland/core/commit/ff7c365bc1d639016c81b7ab9dc0b58baf93e79a @wibus-wee 
- perf!: 将 `webhook` 配置项重命名为 `webhooks` https://github.com/mogland/core/commit/7117ac06d16a2d4bba69c89d182490b1a48fb27b @wibus-wee 
- perf: 标签搜索返回所有字段的数据 #618 @wibus-wee 
- feat: Helper 资源服务 #620 @wibus-wee 
- perf: 取消控制台下载代理 #627 @wibus-wee 
- docs: 重新设计 README 介绍 #641 @wibus-wee 
- ci: lint CI #647 @AkaraChen 
- feat: 活动传输器支持泛型和移除 Observable 类型 #663 @wibus-wee 
- perf: 更多的 RpcException 和拓展支持 #664  @MYXXTS 

## Console

- vite: 移除 `manualChunks` 选项 https://github.com/mogland/console/commit/72b1d9fe15ab90f5abd449a0dca183c17e018194 @wibus-wee 
- feat: 为内置控制台而生的 `jump` 方法 https://github.com/mogland/console/pull/97 @wibus-wee 
- ci: 动态获取 `index-x.{css,js}` 文件名 https://github.com/mogland/console/commit/c4de9225938a6ce8179a19acb3f02e6d31b235af @wibus-wee
- perf: 检查用户服务状态再检验 Token 合法性 https://github.com/mogland/console/commit/3fca2d2315f4784cef9829b4f0859547d391b2bd @wibus-wee
- fix: 出现多重 `jump` 方法导致内置控制台无限循环（ Since from console#97 ） https://github.com/mogland/console/pull/99 @MYXXTS 
- feat: 主题市场与编辑页面 https://github.com/mogland/console/pull/101 @wibus-wee 
- feat: 站点标题 SEO 优化 https://github.com/mogland/console/pull/106 @wibus-wee 

## Docs

- config: 控制台配置 https://github.com/mogland/mog-docs/commit/61e7ca15368711ccf0b60577ba5cc8545abb034b @wibus-wee 
- usage: 内置控制台使用指南 https://github.com/mogland/mog-docs/commit/d07593a326fc4b6466a49a8f39f09fdd9ed2635d @wibus-wee 
- dev: 主题简易开发文档 https://github.com/mogland/mog-docs/commit/6caac630aa6b07ae3131661eaef64dc1123863b6 @wibus-wee 

## RFCs

- rfc: 主题系统 https://github.com/mogland/rfcs/pull/5 @wibus-wee 

## Dev Organization

- theme: 新的 Tiny 主题 [mogland-dev/mog-theme-tiny-ejs](https://github.com/mogland-dev/mog-theme-tiny-ejs) @wibus-wee 
- theme: Single 主题 [mogland-dev/mog-theme-single](https://github.com/mogland-dev/mog-theme-single) @MYXXTS 

## Core Organization

- awesome: 自动收集与生成 Mog 生态列表和生态索引 [mogland/awesome-mog](https://github.com/mogland/awesome-mog) @wibus-wee 
- feat: 主题评论 Web Component 组件 [mogland/mog-comments-wc](https://github.com/mogland/mog-comments-wc) @wibus-wee & @jwcjs

---

- #661

**Comment by MYXXTS** [comment]
好耶
